### ISSUE TITLE
Fix installing from deb file

### ISSUE THREAD

**Issue by kirb** [Sileo/Sileo#10]
The support for installing a deb from file hasn’t worked in some time. Sileo crashes after tapping “Open in Sileo” (e.g. from Safari or Files).

**Comment by Tt2015019881988** [comment]
👍👍👍👍👍👍

**Comment by Tt2015019881988** [comment]
> The support for installing a deb from file hasn’t worked in some time. Sileo crashes after tapping “Open in Sileo” (e.g. from Safari or Files).
