### ISSUE TITLE
Website suggestion

### ISSUE THREAD

**Issue by Tropix126** [Sileo/Sileo#108]
Hello, since the Discord invite seems to be invalid, I was unsure where to contact someone about this. I've noticed that https://getsileo.app/ imports the jQuery library, but only ever utilizes it for one line of code (relating to the navbar). This can easily be replaced with a vanilla JS snippet removing the need for this library, and possibly improving load times for lower end devices.

```js
const header = document.querySelector('.header');
window.addEventListener('scroll', () => {
    if (window.pageYOffset != 0) {
        header.classList.add('scrolled');
    } else {
        header.classList.remove('scrolled');
    }
});
```
This is probably the wrong place to suggest something like this, but it may be of use to someone.

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/111895110-4945fa80-89de-11eb-91d5-7d685392aecf.png)
For reference this is what would be replaced.

**Comment by Diatrus** [comment]
@23Aaron

**Comment by elihwyma** [comment]
@23Aaron

**Comment by captinc** [comment]
@23Aaron

**Comment by DanKGooGLy** [comment]
Bump
