### ISSUE TITLE
Fix dark blur on queue bar

### ISSUE THREAD

**Issue by kirb** [Sileo/Sileo#11]
![IMG_97229BA0FDB3-1](https://user-images.githubusercontent.com/773309/79827002-59bfb080-83dc-11ea-816c-c5cf67a7b6c0.jpeg)

**Comment by coolstar** [comment]
Issue not present here on 12.4 simulator

**Comment by sukarodo** [comment]
issue is apparent on my iOS 13.4.5 iPad6,12 as well. Translucent Queue bar.

**Comment by coolstar** [comment]
Fixed on 1.9 tree (since more components from this 2.x tree are merged in there)
