### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by barronhee** [Sileo/Sileo#110]
![image](https://user-images.githubusercontent.com/80624155/112590635-1d8f9e00-8e3e-11eb-8b50-88a2bf1a3886.png)
Sileo was unable to acquire root permissions. Please reinstall Sileo using ssh.
Device : Iphone 7 plus
Ios : 14.3
Jailbreak tools: unc0ver 6.1.1

**Comment by Diatrus** [comment]
This is not the place to report bugs for unsupported forks of Sileo. Please contact whoever broke it and switch to a jailbreak tool that properly supports it when one releases.
