### ISSUE TITLE
Badge not disappearing after installing/respringing 

### ISSUE THREAD

**Issue by SebastianRasch** [Sileo/Sileo#126]
This problem exists since several years already. Zebra can do it and so can you guys, come on! 💪🏻

Problem: One gets a new update in Sileo for whatever tweak and a badge on the Sileo app icon alongside to show that there's an update pending. After installing said update and respringing, Sileo would still show the badge, falsely indicating there's a pending update. 
Only upon reopening Sileo the badge disappears. 

How it should be: The badge should be gone automatically after respring/installation of the update.

**Comment by elihwyma** [comment]
This has been fixed in 2.1 which is currently in public beta testing on the Odyssey repo

**Comment by SebastianRasch** [comment]
Nice, thanks guys!
