### ISSUE TITLE
Sources tab shows an empty page

### ISSUE THREAD

**Issue by Abeldvlpr** [Sileo/Sileo#129]
Sileo version: 2.0.3
iOS 12.4 iPhone 12,1 (11), Taurine 1.0.2

Every time i open Sileo and go the the Sources tab it shows an empty page with a return button. When tapping this return button i get to the sources list.

Expected behavior: getting the sources list when tapping on the Sources tab

Video of the issue: 

https://user-images.githubusercontent.com/300872/113976686-bf9d8600-9841-11eb-997e-96925ae4f2eb.mov

**Comment by CanerKaraca23** [comment]
How can you use Taurine on iOS 12.4?

**Comment by elihwyma** [comment]
1; You can't 
2: How is that related
