### ISSUE TITLE
RocketBootstrap Update 

### ISSUE THREAD

**Issue by RogueStatus23** [Sileo/Sileo#137]
RocketBootstrap update gave me errors can’t update, install or remove anything from Sileo. Lost most preference bundles from my tweaks as well. Error RocketBootstrap depends org.coolstar.libhooker I needed to update my preference loader as well but can’t add or remove anything now.
![5F0C2BA7-2D91-4F66-A137-AA985B0F2C92](https://user-images.githubusercontent.com/82721697/115119872-cc1f8e00-9f67-11eb-8cda-76b9c246af66.png)

**Comment by Diatrus** [comment]
Not a Sileo issues
