### ISSUE TITLE
« Unable to fetch some archives » when attempting to install openssh

### ISSUE THREAD

**Issue by Muda42** [Sileo/Sileo#151]
**iOS Version:**
14.6

**Jailbreak:**
Odysseyra1n

**Sileo version:**
2.1

**Issue:**
When attempting to install _openssh_ from Procursus, I get this message:
![image](https://user-images.githubusercontent.com/36187136/119526720-ec6d1480-bd7f-11eb-8a11-53941f071aae.png)
I already tried running the mentioned commands to no avail. I tried doing the same on Sileo 2.0.3 and no problems there.

**Comment by Zaq14rfv** [comment]
reboot your device and re-jailbreak

**Comment by Muda42** [comment]
Already did that

**Comment by Zaq14rfv** [comment]
> Already did that

try to open libhooker safe mode app,tap "restart springboard "🌝

**Comment by elihwyma** [comment]
> 
> 
> > Already did that
> 
> try to open libhooker safe mode app,tap "restart springboard "🌝

This is a Sileo bug, you can't fix it by restarting springboard etc

**Comment by Diatrus** [comment]
A workaround is just installing openssh-server

**Comment by Muda42** [comment]
I fixed it by installing Zebra

**Comment by Zaq14rfv** [comment]
> I fixed it by installing Zebra

🌝🌚🌝🌚
