### ISSUE TITLE
Can not install package

### ISSUE THREAD

**Issue by Zaq14rfv** [Sileo/Sileo#154]
Jailbreak with checkra1n 0.12.4
iPadOS 14.7
iPad Air 2
Sileo 2.0.2-tale1
![IMG_0883](https://user-images.githubusercontent.com/78459878/120068694-9c11f180-c0b4-11eb-9614-079063832768.png)

**Comment by Diatrus** [comment]
This is not official Sileo.

**Comment by deontw** [comment]
> Jailbreak with checkra1n 0.12.4
> iPadOS 14.7
> iPad Air 2
> Sileo 2.0.2-tale1
> ![IMG_0883](https://user-images.githubusercontent.com/78459878/120068694-9c11f180-c0b4-11eb-9614-079063832768.png)

Just use Odysseyra1n
