### ISSUE TITLE
Can't install openssh on iPhone 6S iOS 14.7.1

### ISSUE THREAD

**Issue by CSab6482** [Sileo/Sileo#165]
https://user-images.githubusercontent.com/53708281/127598711-6de98aac-ce02-4bbc-a485-321c2ed44fdb.mp4

**Comment by deontw** [comment]
Just Install openssh-server.

**Comment by deontw** [comment]
Or use sudo apt install openssh

**Comment by CSab6482** [comment]
> Just Install openssh-server.

This did it, thanks! I'm still curious to know why it won't install however.
