### ISSUE TITLE
Blank startup screen

### ISSUE THREAD

**Issue by Ngsaints29** [Sileo/Sileo#196]
When going into Sileo 2.2.3 sometimes it gives me a blank screen on startup to fix this I have to go to sources and refresh sources to fix this issue 

Taurine 1.0.7
Sileo 2.2.3
iPhone 12 Pro iOS 14.3

**Comment by elihwyma** [comment]
Do you have a recording of this happening? It may be caused by a slow network connection when loading the featured info.
