### ISSUE TITLE
Payment Provider breaks when /payment_endpoint's URL doesn't have a trailing slash

### ISSUE THREAD

**Issue by tale** [Sileo/Sileo#209]
Recently, the advertised `payment_endpoint` on Chariz had changed and dropped the slash. Within minutes we received reports of Sileo directing to 404 pages and noticed that Sileo doesn't add the trailing slash if it's missing leading to URLs like `https://chariz.com/api/sileoinfo` instead of `https://chariz.com/api/sileo/info`.

Sileo gets the endpoint here, so it might make sense to check for a trailing slash and append one if necessary: https://github.com/Sileo/Sileo/blob/01998a12efbf6e7760cf15c22894428c56a2cdd0/Sileo/Backend/Payment%20Manager/PaymentManager.swift#L60

**Comment by elihwyma** [comment]
Resolved in https://github.com/Sileo/Sileo/commit/17c0b54484b302c2554e2f29702fc4154ee1d55e
