### ISSUE TITLE
Sileo doesn’t display download error to user

### ISSUE THREAD

**Issue by HexCodeFFF** [Sileo/Sileo#211]
I’m currently having issues with a hash mismatch on download
![A2F4A296-5D03-484C-836D-B2AF7B249445](https://user-images.githubusercontent.com/35177464/151722433-6e4e0356-a986-4870-837a-77434b34c420.png)
![2995F17D-8D01-43B0-902A-744515A5DC4C](https://user-images.githubusercontent.com/35177464/151722434-19c123dd-cca8-40b6-9aa9-90de4c769246.jpeg)
But when attempted within sileo, it stops on the download screen instead of displaying the error or cancelling download.
![E38627ED-C84F-43C7-82DB-9907DAF76333](https://user-images.githubusercontent.com/35177464/151722439-c57caba6-324a-46ec-87b0-463cd76dd01e.png)

**Comment by elihwyma** [comment]
This is something that will come in a future update alongside https://github.com/Sileo/Sileo/issues/255#issue-1501726014, I will close this issue for now and continue updating there.
