### ISSUE TITLE
Trying to change tint in iOS 12.5.5 crashes Sileo

### ISSUE THREAD

**Issue by DLordStarkiller** [Sileo/Sileo#213]
Jailbroken with odysseyra1n (iPhone 5s) running iOS 12.5.5 and as the title says, trying to select a tint color causes Sileo to crash

**Comment by faisl887** [comment]
> Jailbroken with odysseyra1n (iPhone 5s) running iOS 12.5.5 and as the title says, trying to select a tint color causes Sileo to crash

**Comment by faisl887** [comment]
> > Jailbroken with odysseyra1n (iPhone 5s) running iOS 12.5.5 and as the title says, trying to select a tint color causes Sileo to crash
> 
>

**Comment by NguyenASang** [comment]
Need someone fixes it pls :(

**Comment by SteveZMTstudios** [comment]
This problem is still exist at 7/17/2022.

**Comment by elihwyma** [comment]
This is a problem with Alderis and the way it is packaged for iOS 12, I will try to find a way to resolve this.
