### ISSUE TITLE
W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No Such File or directory)

### ISSUE THREAD

**Issue by NguyenHai79** [Sileo/Sileo#266]
This error occurs when installing Sileo-Xina-Beta-5.ipa, not updating the source and turning off automatic source update.
(XinaA15 1.1.7.2 on 12promax 15.1.1)
can you fix it?

**Comment by elihwyma** [comment]
This is a bug with XinaJB, nothing that can be fixed by Sileo.
