### ISSUE TITLE
Sileo Nightly crashes on start since last update.

### ISSUE THREAD

**Issue by tribbedev** [Sileo/Sileo#300]

**Comment by lisiyaki** [comment]
experiencing this issue as well, iOS 15.3, iPhone 13 Pro, Dopamine beta 8

**Comment by tribbedev** [comment]
I forgot to include:
iPhone 13 Pro 15.1

**Comment by LCRich2001** [comment]
Same here. iPhone 13 on iOS 15.3 with Dopamine/Fugu15Max Beta 8.

**Comment by lavavex** [comment]
if you have Newterm or ssh installed, run `apt install org.coolstar.sileo` as root to get Sileo stable installed
