### ISSUE TITLE
Switch to shared sources.list.d directory

### ISSUE THREAD

**Issue by kirb** [Sileo/Sileo#31]
We currently put sources at /etc/apt/sileo.list.d/sileo.sources. Let’s have them be shared with other APT clients such as `apt` and Cydia by putting them in the default path, /etc/apt/sources.list.d/sileo.sources.

This requires migration from the old path to new. We also need to ensure we aren’t adding duplicate repos (migrated, or our defaults) that were already added outside of Sileo. @sbingner has done part of this work already.

**Comment by coolstar** [comment]
Electra and Chimera already have sources at /etc/apt/sources.list.d/sileo.sources

**Comment by M1staAwesome** [comment]
are you sure about that? all of my devices w/ sileo are at sileo.list.d instead of sources.list.d

**Comment by coolstar** [comment]
Irrelevant to most of Sileo's supported jailbreaks/bootstraps. Closing.
