### ISSUE TITLE
Error: Didn't find achitectures DPKGArchitecture() in (repo link)

### ISSUE THREAD

**Issue by ZxverOwner** [Sileo/Sileo#328]
i get this error when i add some repos

**Comment by elihwyma** [comment]
Then either you're on rootless and the repo doesn't support rootless or vice versa. Not a Sileo problem.

**Comment by lich4** [comment]
This error requires to add "iphoneos-arm64" to Architectures in 'Release' file in cydia repository, for example:
```
Origin: ...
Label: ...
Suite: stable
Version: 1.0
Codename: ..
Architectures: iphoneos-arm iphoneos-arm64 iphoneos-arm64e
Components: main
Description: ...
```
