### ISSUE TITLE
Verify Proper RTL support

### ISSUE THREAD

**Issue by coolstar** [Sileo/Sileo#33]
Verify proper RTL support with one of the PR's that adds support for an RTL language

**Comment by Mexicooll** [comment]
![image](https://user-images.githubusercontent.com/80504415/111573216-50af9e80-8767-11eb-9a32-a65e3dc06c90.png)

**Comment by Mexicooll** [comment]
iPhone SE iOS 14.4 FFPDVGBPPLJN****
