### ISSUE TITLE
Install Sileo?

### ISSUE THREAD

**Issue by CydiaGod666** [Sileo/Sileo#35]
redacted

**Comment by kirb** [comment]
I’d recommend you **not** build this if you don’t have experience with iOS app development or aren’t able to work through a few build errors. Stick to official releases only.

**Comment by 10Meisterbaelle** [comment]
You need to add this repo: [repo.getsileo.app](cydia://url/https://cydia.saurik.com/api/share#?source=https://10Meisterbaelle.gitlab.io/jailbreak/) (Click to add to Cydia)
