### ISSUE TITLE
Minimized qeue has a white border in dark mode on iPads

### ISSUE THREAD

**Issue by greybaron** [Sileo/Sileo#40]
In light mode it always looks correct. And toggling the theme or opening and closing the qeue doesn‘t change the white outline, but it is not visible while the queue is open.
![D65EAE8C-6977-4AEE-A80F-A4C0F8C7F00E](https://user-images.githubusercontent.com/20914657/81988103-308ceb80-963b-11ea-90be-ec20c6ee9877.jpeg)

**Comment by captinc** [comment]
Will be handled shortly in an upcoming version
