### ISSUE TITLE
Search tab QOL change

### ISSUE THREAD

**Issue by CoolOrbit** [Sileo/Sileo#42]
Currently when you search for something in Sileo and then try to select a tweak, it will only dismiss the keyboard and then you have to select it again.

I’m sure most people, myself included, would prefer if it worked like most stuff where when you select a tweak it will go to that tweaks page and dismiss the keyboard at the same time rather than requiring two inputs

**Comment by captinc** [comment]
Will be handled shortly in an upcoming version
