### ISSUE TITLE
Sileo new section

### ISSUE THREAD

**Issue by Ngsaints29** [Sileo/Sileo#44]
Hi when refreshing sources the new tab doesn’t update automatically like other package managers do when refreshing them. I have to exit Sileo and then go back into Sileo to the new tab for it to show me all the new tweaks. I’m on iPhone 11 iOS 13.5 on Sileo 1.8.2

**Comment by Kaikhong** [comment]
I also have this issue

**Comment by Ngsaints29** [comment]
Still exists in 1.8.3

**Comment by Ngsaints29** [comment]
Still present in 1.8.5
