### ISSUE TITLE
Possible Issue with Markdown Parser

### ISSUE THREAD

**Issue by JeffResc** [Sileo/Sileo#45]
I just wanted to report that there might be an issue with the way that the markdown parser interprets tables in the depiction pages. In my package, SongShare (dev.jeffresc.songshare), it looks like this:
![image](https://user-images.githubusercontent.com/5752328/83695100-6fbdb500-a5c7-11ea-8c82-a61e5fbad95e.png)

Is this an issue with my markdown or an issue with the markdown parsing?

Thanks!

**Comment by 23Aaron** [comment]
Hi there, this isn’t an issue, your markdown contains HTML tags which are purposefully not parsed by Sileo.

**Comment by JeffResc** [comment]
Thanks, but I [loaded the Sileo depiction page in my browser](https://repo.dynastic.co/sileo-depiction/315679034291781632/) and it's definitely markdown, not HTML. I actually directly copy and pasted the markdown into [an online markdown editor/viewer](https://stackedit.io/app#) and it rendered just fine

**Comment by jamiebishop** [comment]
yeah that’s markdown. looks like sileo doesn’t render tables

**Comment by kirb** [comment]
UITextView/NSAttributedString doesn’t support tables unfortunately.

**Comment by jamiebishop** [comment]
Ah right, forgot that this is just a `UITextView`
