### ISSUE TITLE
Sileo crashed when view some tweaks

### ISSUE THREAD

**Issue by vuluanls** [Sileo/Sileo#46]
I use iPhone 11 Pro Max, iOS 13.5 with unc0ver jailbreak. I installed Sileo on repo.getsileo.app 
Everything work fine, but I get crashed when I view some tweaks, ex: AutoScroll
Please re-check it

**Comment by 10Meisterbaelle** [comment]
Do you mean AutoScroller? If no, on what repo is it? I want to check if I have the same issue.

**Comment by Diatrus** [comment]
Closing: cannot reproduce + stale
