### ISSUE TITLE
Allow easy exit from Sileo Safe Mode

### ISSUE THREAD

**Issue by brennanleblanc0** [Sileo/Sileo#48]
Currently it seems there is no easy way to restart the springboard to exit Safe Mode. Currently what I have been doing is to reinstall a tweak that require a respring. I am currently using unc0ver on iOS 13.5

**Comment by 23Aaron** [comment]
Could you please attach a screenshot of the Safe Mode prompt?

**Comment by demhademha** [comment]
Are you using unc0ver

**Comment by brennanleblanc0** [comment]
Yes. I stated that in the initial comment. I’m guessing this is causing the issue?

**Comment by demhademha** [comment]
Yes, this is a known issue with unc0ver

**Comment by worldlydev** [comment]
A possible solution for this could be to include a toggle for restarting SpringBoard in Sileo such as in Zebra.

![BE571DC0-6A09-4DD9-9015-B47D8F4B1E6A](https://user-images.githubusercontent.com/51668635/85233358-d9cabc80-b405-11ea-8f67-b6f32860cca0.jpeg)
![B499AD4A-8F5A-423F-A70D-1C8199A6877E](https://user-images.githubusercontent.com/51668635/85233359-dc2d1680-b405-11ea-91e7-4a87fd985c2d.jpeg)

**Comment by coolstar** [comment]
Not an issue with Sileo itself
