### ISSUE TITLE
Camera black screen

### ISSUE THREAD

**Issue by MaoSuYu** [Sileo/Sileo#49]
When using Sileo on UN, the camera will appear black screen from time to time, which can only be solved by ldrestart

**Comment by M1staAwesome** [comment]
This is for issues related to Sileo, not unc0ver.

**Comment by MaoSuYu** [comment]
It's about Sileo, if you're not a sileo developer please shut up!

**Comment by M1staAwesome** [comment]
If you don't know what you're talking about please shut up!

A package manager isn't going to break your camera functionality, use some common sense.

**Comment by Skittyblock** [comment]
Hello, I'm a Sileo developer. I'm fairly certain the Sileo is not the one causing the issue here because, as @M1staAwesome said, it doesn't modify camera functionality. I recommend you bring up your issue with the maintainer of whichever jailbreak you experience it on. Are you positive this only happens while using Sileo on unc0ver? You may have some other package that is causing the issue.

**Comment by MaoSuYu** [comment]
Sileo really do exist such problems in the UN, and has had a lot of feedback about this problem, I have in my three devices were tested, is due to the problem sileo, that can mean sileo is imperfect in the UN, and the problem is not the installation of the sileo immediately after, so this is a hidden problem! With Cydia, Zebra didn't have this problem! Because this problem is not easily detected, if you want to verify it, you can simply install your own test

**Comment by Skittyblock** [comment]
I'm running Sileo on my device with no problems, along with a lot of other people. If you could provide some kind of evidence that points towards Sileo actually being the culprit, I'd be happy to help fix it.

**Comment by MaoSuYu** [comment]
Because the problem can be solved with LDrestart, if the device is a regular respring or LDrestart, the problem will probably not be noticed, which makes it very difficult to detect! But one thing is for sure, most of the devices that reported this problem were iOS13.5

**Comment by Skittyblock** [comment]
Er, I never use ldrestart. I'm just going to close this issue because there's nothing pointing to Sileo causing it, besides it being present along with many other packages on your device.
