### ISSUE TITLE
Ignoring Updates shows up under updates

### ISSUE THREAD

**Issue by DebianArch64** [Sileo/Sileo#51]
So yes the functionality of clicking the “Upgrade All” button chooses everything except the ignored update, but it still shows up.  In this case the ignored update is Sileo Safe Mode(on unc0ver device).
![02E2F528-53CB-4B79-A1CF-48D96B2588B4](https://user-images.githubusercontent.com/63203414/84294081-455f8080-ab0e-11ea-841d-0802b732f5a8.jpeg)

**Comment by Chanhapple1** [comment]
Sileo

**Comment by captinc** [comment]
Packages that have "Ignore Upgrades" enabled will be relocated to more a suitable place shortly
