### ISSUE TITLE
Everytime I try signing out of Chariz, Sileo just crashes.

### ISSUE THREAD

**Issue by agile-x86** [Sileo/Sileo#57]
**Device:** iPad Mini 5 (Wifi)
**Version:** 13.5
**Jailbreak:** Unc0ver, with Sileo install from repo.getsileo.app
**Crash log:** https://ghostbin.co/paste/mekyz
**Video:** https://gofile.io/d/LgWBxU

Title. Everytime I try signing out of Chariz on Sileo (In which it just shows an empty page), it will just crash on my iPad Mini 5.

**Comment by coolstar** [comment]
Fixed in 1.8.7
