### ISSUE TITLE
On some repos, there is no "View Depiction" button for WebView Depictions

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Sileo/Sileo#58]
For example, [repo.nepeta.me](https://repo.nepeta.me/)

**Comment by 10Meisterbaelle** [comment]
Even if you add a depiction compiler (or however it is called), it should still be fixed.

**Comment by demhademha** [comment]
Napeta hasn't updated her repo with compatibility with sileo depictions...

**Comment by 10Meisterbaelle** [comment]
> Napeta hasn't updated her repo with compatibility with sileo depictions...  

Yeah, but if you don't have them, there is a button called "View depiction" that shows the web view depictions.

**Comment by salemkmsr** [comment]
> Even if you add a depiction compiler (or however it is called), it should still be fixed.

**Comment by salemkmsr** [comment]
> > Even if you add a depiction compiler (or however it is called), it should still be fixed.
> 
>

**Comment by salemkmsr** [comment]
> For example, [repo.nepeta.me](https://repo.nepeta.me/)

**Comment by salemkmsr** [comment]
> > For example, [repo.nepeta.me](https://repo.nepeta.me/)
> 
>

**Comment by Diatrus** [comment]
Closing: stale and nepeta repo doesn't even exist anymore.
