### ISSUE TITLE
Tweaks from the new section disappearing

### ISSUE THREAD

**Issue by Ngsaints29** [Sileo/Sileo#60]
I've been noticing that when refreshing sources sometimes it updates and sometimes it doesn't. But I noticed this new thing where the tweak names disappear and just show the time and date. ![image](https://user-images.githubusercontent.com/51883775/88855096-5b112e00-d1c0-11ea-9960-54e77affca7e.jpeg)

**Comment by Ngsaints29** [comment]
Sileo 1.8.7 
Odyssey beta 2
iPhone 11 iOS 13.5

**Comment by salemkmsr** [comment]
> Sileo 1.8.7 
> Odyssey beta 2
> iPhone 11 iOS 13.5

**Comment by salemkmsr** [comment]
> > Sileo 1.8.7 
> > Odyssey beta 2
> > iPhone 11 iOS 13.5 
> 
>

**Comment by salemkmsr** [comment]
> I've been noticing that when refreshing sources sometimes it updates and sometimes it doesn't. But I noticed this new thing where the tweak names disappear and just show the time and date. ![image](https://user-images.githubusercontent.com/51883775/88855096-5b112e00-d1c0-11ea-9960-54e77affca7e.jpeg)

**Comment by Diatrus** [comment]
Fixed in a more recent Sileo version.
