### ISSUE TITLE
Adding Source clears install queue

### ISSUE THREAD

**Issue by SirNapkin1334** [Sileo/Sileo#63]
If you add a source, but have apps in the queue, they are all removed. 

How to reproduce:  
1. Queue a few apps
2. Add new source
3. Observe - there are no apps in the queue.

**Comment by salemkmsr** [comment]
اي

**Comment by salemkmsr** [comment]
> If you add a source, but have apps in the queue, they are all removed. 
> 
> 
> 
> How to reproduce:  
> 
> 1. Queue a few apps
> 
> 2. Add new source
> 
> 3. Observe - there are no apps in the queue.

**Comment by salemkmsr** [comment]
> > If you add a source, but have apps in the queue, they are all removed. 
> > 
> > 
> > 
> > How to reproduce:  
> > 
> > 1. Queue a few apps
> > 
> > 2. Add new source
> > 
> > 3. Observe - there are no apps in the queue.
> 
>

**Comment by salemkmsr** [comment]
> If you add a source, but have apps in the queue, they are all removed. 
> 
> 
> 
> How to reproduce:  
> 
> 1. Queue a few apps
> 
> 2. Add new source
> 
> 3. Observe - there are no apps in the queue.

**Comment by captinc** [comment]
Handled
