### ISSUE TITLE
Packix depictions not updating

### ISSUE THREAD

**Issue by ca13ra1** [Sileo/Sileo#70]
When I adjust my Packix depiction pages, they do not appear updated even after killing the app, removing source then adding source again. 

Cydia and Zebra have no problems updating when I view the packages, seems to be only Sileo.

**Comment by azoo61** [comment]
> When I adjust my Packix depiction pages, they do not appear updated even after killing the app, removing source then adding source again. 
> 
> 
> 
> Cydia and Zebra have no problems updating when I view the packages, seems to be only Sileo.
