### ISSUE TITLE
Can't add source via 'sileo://' URL

### ISSUE THREAD

**Issue by hwittenborn** [Sileo/Sileo#78]
I'm trying to integrate an "Add to Sileo" button into my repo's website, but everytime it opens Sileo, it keeps saying "Invalid URL". Here's the URL scheme I'm using:

`sileo://source/https://repo.example.com/`

I'm just copy-pasting the same format from other repos to mine, neither mine nor the orignal URLs from which I'm basing mine are seeming to work.

Is there something I'm doing wrong?

**Comment by HeyItsMicro** [comment]
I have this issue as well

**Comment by hwittenborn** [comment]
Same here(says 2.0.0b9, sounds like it's the same though)

**Comment by hwittenborn** [comment]
@HeyItsMicro Mods on the Sileo Discord's saying it's just a bug, here's a link if you want to look at it: https://discord.com/channels/468422899716456498/679875337358016545/800310724202594304
