### ISSUE TITLE
Color picker bug!

### ISSUE THREAD

**Issue by ZonatedTech** [Sileo/Sileo#91]
This isn’t really a big and bad bug but I just like when things work as they should you know? The color picker gets pushed down causing the done and cancel buttons not to show. Thank you for your time if you are reading this and take your time on future bug fixes and updates with Sileo! (Btw this screenshot is a full screenshot the bottom is not cropped)
![AFFA81BA-91B5-41B5-93BC-BDFFEC71DE5B](https://user-images.githubusercontent.com/63753030/111400290-0c53ce00-8695-11eb-8e36-4d51bbdfb4d8.jpeg)

**Comment by CharlieWhile13** [comment]
This is a known bug and is being looked into

**Comment by devhot1984** [comment]
# [Developer](https://dandeveloper.carrd.co)

**Comment by captinc** [comment]
Will be handled shortly in an upcoming version
