### ISSUE TITLE
Cannot install packages

### ISSUE THREAD

**Issue by theMIGwelder** [Sileo/Sileo#97]
After trying to install 20 updates at once and taping the “Show Details” button, Sileo crashed. 

When I returned, A message that was along the lines of “repairing dpkg” appeared and Sileo exited again. 

When I returned a second time, most of the packages seem to have installed. When trying to reinstall the remaining ones, Sileo gives me this error “held packages were changed and -y was used without - -allow-change-held-packages. 

I’m unable to install or upgrade anything at the moment.

**Comment by captinc** [comment]
This is likely a problem with your specific jailbreak setup rather than a problem with Sileo itself. Will close this for now, but if you (or other people) can reliably reproduce the problem, please let me know.
